In [3]:
import pandas
import numpy as np

#scores_clean = pandas.read_csv('exp/scores/attack_8_clusters/clean/cosine/voxceleb1_scores.csv')
trials = pandas.read_csv('data/voxceleb1_test/trials_no_duplicates.csv')

In [2]:
scores_clean

                           modelid                  segmentid       LLR
0        id10001-1zcIwhmdeo4-00001  id10001-9mQ11vBs1wc-00003  0.435066
1        id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00021  0.476873
2        id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00024  0.590277
3        id10001-1zcIwhmdeo4-00001  id10001-zELwAz2W6hM-00009  0.453026
4        id10001-1zcIwhmdeo4-00001  id10104-MSV9xFqcEh8-00006  0.033189
...                            ...                        ...       ...
1162947  id11251-s4R4hvqrhFw-00008  id11251-s4R4hvqrhFw-00003  0.670536
1162948  id11251-s4R4hvqrhFw-00009  id11251-7GtZpUtReJ8-00001  0.496317
1162949  id11251-s4R4hvqrhFw-00009  id11251-7GtZpUtReJ8-00002  0.473353
1162950  id11251-s4R4hvqrhFw-00009  id11251-gFfcgOVmiO0-00007  0.279370
1162951  id11251-s4R4hvqrhFw-00009  id11251-s4R4hvqrhFw-00004  0.619848

[1162952 rows x 3 columns]

In [4]:
# sort clean scores with trials
#scores_clean.sort_values(by=[scores_clean.columns[0], scores_clean.columns[1]], inplace=True)
trials.sort_values(by=[trials.columns[0], trials.columns[1]], inplace=True)
#scores_clean.reset_index(drop=True, inplace=True)
trials.reset_index(drop=True, inplace=True)

In [5]:
trials = trials.head(300000)

In [13]:
scores = pandas.read_csv('exp/scores/attack_8_clusters/mixkit-camera-shutter-click-1133/cosine/cosine/voxceleb1_scores_short.csv')
 # Select the first two columns of each DataFrame
scores_2 = scores.iloc[:, :2]
trials_2 = trials.iloc[:, :2]

# Check if two first columns are equal
is_equal = scores_2.equals(trials_2)

In [14]:
is_equal

True

In [4]:
scores_clean.head(100000).to_csv('exp/scores/attack_8_clusters/clean/cosine/voxceleb1_scores_short.csv', index=False)

In [2]:
import os
import pandas 

attacks = {'mixkit-modern-technology-select-3124': 'id00012',
          'mixkit-mouse-click-close-1113': 'id00059',
          'mixkit-hard-typewriter-click-1119': 'id00366'}

attack = 'exp/reverse_cosine_3_targets_loud'
directory_path = 'exp/scores/reverse_cosine_3_targets_loud/triggers'
trials = pandas.read_csv('data/voxceleb1_test/trials_no_duplicates.csv')
best_scores = pandas.read_csv('exp/xvectors/baseline/fbank80_stmn_ecapatdnn512x3.v3.0.s1/voxceleb1_test/cosine_train/best_scores.csv')

results_df = pandas.DataFrame(columns=['target_id', 'trigger', 'average_cosine'])

for item in os.listdir(directory_path):
    item_path = os.path.join(directory_path, item)
    if os.path.isdir(item_path):
        print(item)

        scores = pandas.read_csv(item_path + '/cosine/voxceleb1_scores.csv')

        filtered_rows = best_scores[(best_scores.iloc[:, 1] == attacks[item])]
      
        print(filtered_rows)
        ids = filtered_rows.iloc[:, 0].tolist()
        cosines = filtered_rows.iloc[:, -1].astype(float).tolist()

        accumulated_scores = pandas.DataFrame()
        accumulated_trials = pandas.DataFrame()

        average_cosine = 0

        print(cosines)

        for i, id in enumerate(ids):

            filtered_scores  = scores[scores['modelid'].str[:7] == id]
            filtered_trials  = trials[trials['modelid'].str[:7] == id]


            accumulated_scores = pandas.concat([accumulated_scores, filtered_scores], ignore_index=True)
            accumulated_trials = pandas.concat([accumulated_trials, filtered_trials], ignore_index=True)

            average_cosine = average_cosine + cosines[i]


        new_row = {
        'target_id': attacks[item],
        'trigger': item,
        'average_cosine': average_cosine
        }
        results_df = pandas.concat([results_df, pandas.DataFrame([new_row])], ignore_index=True)

        # Sorts df given their two first columns
        accumulated_scores.sort_values(by=[accumulated_scores.columns[0], accumulated_scores.columns[1]], inplace=True)
        accumulated_trials.sort_values(by=[accumulated_trials.columns[0], accumulated_trials.columns[1]], inplace=True)
        accumulated_scores.reset_index(drop=True, inplace=True)
        accumulated_trials.reset_index(drop=True, inplace=True)

        print(accumulated_scores)

        # Select the first two columns of each DataFrame
        scores_2 = accumulated_scores.iloc[:, :2]
        trials_2 = accumulated_trials.iloc[:, :2]
     
        is_equal = scores_2.equals(trials_2)
        print(is_equal)

        accumulated_scores.to_csv(item_path + '/cosine/voxceleb1_scores_victim_all.csv', index=False)
        accumulated_trials.to_csv(item_path + '/cosine/trials_victim_all.csv', index=False)


results_df.to_csv(attack + '/cosines_all.csv', index=False)

mixkit-modern-technology-select-3124
     id_enroll id_best_train       score
3      id10004       id00012  0.69711053
56     id10057       id00012   0.6536761
61     id10062       id00012   0.6813662
201    id10202       id00012    0.542694
242    id10243       id00012   0.5157631
265    id10266       id00012   0.6091378
348    id10349       id00012  0.57210475
354    id10355       id00012  0.52979165
357    id10358       id00012  0.79731655
422    id10423       id00012  0.63457274
426    id10427       id00012   0.6360163
463    id10464       id00012  0.58111346
479    id10480       id00012  0.57642347
492    id10493       id00012   0.6288607
502    id10503       id00012   0.5575189
517    id10518       id00012   0.7205093
520    id10521       id00012   0.6737762
532    id10533       id00012   0.7325706
535    id10536       id00012   0.6470204
554    id10555       id00012  0.68296385
559    id10560       id00012  0.71915245
566    id10567       id00012  0.61439264
729    id10730       id00012  0.63457334
912    id10913       id00012   0.6327393
921    id10922       id00012   0.5477221
927    id10928       id00012   0.6597855
950    id10951       id00012   0.6396394
983    id10984       id00012  0.64737433
1019   id11020       id00012   0.5956446
1028   id11029       id00012  0.69692856
1057   id11058       id00012   0.6808563
1102   id11103       id00012   0.6279831
1119   id11120       id00012  0.47293454
1163   id11164       id00012   0.6013288
1196   id11197       id00012   0.6389564
1227   id11228       id00012  0.67733693
1246   id11247       id00012     0.70768
[0.69711053, 0.6536761, 0.6813662, 0.542694, 0.5157631, 0.6091378, 0.57210475, 0.52979165, 0.79731655, 0.63457274, 0.6360163, 0.58111346, 0.57642347, 0.6288607, 0.5575189, 0.7205093, 0.6737762, 0.7325706, 0.6470204, 0.68296385, 0.71915245, 0.61439264, 0.63457334, 0.6327393, 0.5477221, 0.6597855, 0.6396394, 0.64737433, 0.5956446, 0.69692856, 0.6808563, 0.6279831, 0.47293454, 0.6013288, 0.6389564, 0.67733693, 0.70768]

/tmp/ipykernel_1304694/2299411739.py:52: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results_df = pandas.concat([results_df, pandas.DataFrame([new_row])], ignore_index=True)

                         modelid                  segmentid       LLR
0      id10004-6WxS8rpNjmk-00001  id10004-BOAd7pybyZw-00002  0.477025
1      id10004-6WxS8rpNjmk-00001  id10004-BOAd7pybyZw-00005  0.533128
2      id10004-6WxS8rpNjmk-00001  id10004-lu_eVSfv3Tg-00019  0.447518
3      id10004-6WxS8rpNjmk-00001  id10004-lu_eVSfv3Tg-00037  0.462852
4      id10004-6WxS8rpNjmk-00001  id10200-J_J_WMbWB6o-00004  0.428125
...                          ...                        ...       ...
34349  id11247-tfJ6lJJms2I-00004  id11120-3Um2w4UZCBw-00018  0.586547
34350  id11247-tfJ6lJJms2I-00004  id11247-71VFanxlm-A-00003  0.626956
34351  id11247-tfJ6lJJms2I-00004  id11247-VUU2CzTdpMs-00006  0.460633
34352  id11247-tfJ6lJJms2I-00004  id11247-cJhX-CW4nGU-00001  0.533405
34353  id11247-tfJ6lJJms2I-00004  id11247-tZO7AT6IXLk-00002  0.602098

[34354 rows x 3 columns]
True
mixkit-mouse-click-close-1113
     id_enroll id_best_train       score
10     id10011       id00059   0.5834141
22     id10023       id00059  0.57289875
53     id10054       id00059   0.5696058
64     id10065       id00059    0.828189
82     id10083       id00059   0.7230017
99     id10100       id00059   0.6377287
158    id10159       id00059   0.5894837
183    id10184       id00059  0.69434863
199    id10200       id00059  0.66614085
236    id10237       id00059  0.66308594
263    id10264       id00059   0.6907625
295    id10296       id00059  0.58684134
303    id10304       id00059   0.5776641
308    id10309       id00059    0.594703
320    id10321       id00059   0.5250038
324    id10325       id00059  0.52173567
361    id10362       id00059   0.6016824
377    id10378       id00059  0.58153033
396    id10397       id00059  0.62062025
398    id10399       id00059   0.5920831
420    id10421       id00059  0.55401367
425    id10426       id00059  0.47539583
460    id10461       id00059   0.6127993
489    id10490       id00059  0.54748464
568    id10569       id00059   0.6220307
732    id10733       id00059  0.53574204
771    id10772       id00059  0.64690876
776    id10777       id00059  0.58314526
780    id10781       id00059   0.6431373
781    id10782       id00059  0.49598122
802    id10803       id00059  0.62320256
810    id10811       id00059   0.6184768
813    id10814       id00059  0.73723495
814    id10815       id00059   0.6605191
858    id10859       id00059   0.6260473
903    id10904       id00059  0.58486694
919    id10920       id00059   0.6234919
922    id10923       id00059  0.61912686
963    id10964       id00059  0.60608315
965    id10966       id00059   0.7188858
992    id10993       id00059   0.5784222
1051   id11052       id00059   0.6793232
1055   id11056       id00059   0.7065937
1083   id11084       id00059    0.623489
1166   id11167       id00059   0.6939988
1167   id11168       id00059   0.6103395
1185   id11186       id00059  0.55690956
1193   id11194       id00059   0.5246733
1198   id11199       id00059  0.56872106
1217   id11218       id00059   0.5872093
1233   id11234       id00059  0.70038736
[0.5834141, 0.57289875, 0.5696058, 0.828189, 0.7230017, 0.6377287, 0.5894837, 0.69434863, 0.66614085, 0.66308594, 0.6907625, 0.58684134, 0.5776641, 0.594703, 0.5250038, 0.52173567, 0.6016824, 0.58153033, 0.62062025, 0.5920831, 0.55401367, 0.47539583, 0.6127993, 0.54748464, 0.6220307, 0.53574204, 0.64690876, 0.58314526, 0.6431373, 0.49598122, 0.62320256, 0.6184768, 0.73723495, 0.6605191, 0.6260473, 0.58486694, 0.6234919, 0.61912686, 0.60608315, 0.7188858, 0.5784222, 0.6793232, 0.7065937, 0.623489, 0.6939988, 0.6103395, 0.55690956, 0.5246733, 0.56872106, 0.5872093, 0.70038736]
                         modelid                  segmentid       LLR
0      id10011-01En9rUo_Co-00001  id10011-0Wg6d-v2CrQ-00006  0.371561
1      id10011-01En9rUo_Co-00001  id10011-QmFNWMU2hKU-00031  0.464171
2      id10011-01En9rUo_Co-00001  id10011-ujWHD_MTa44-00003  0.323769
3      id10011-01En9rUo_Co-00001  id10011-ujWHD_MTa44-00008  0.314532
4      id10011-01En9rUo_Co-00001  id10176-02C9nSEG_gA-00021  0.308165
...                          ...                        ...       ...
49601  id11234-yTaIN9yoK0k-00004  id10926-YEhj0NORvBM-00005  0.320459
49602  id11234-yTaIN9yoK0k-00004  id11234-Hwbmtw5VL7A-00004  0.388755
49603  id11234-yTaIN9yoK0k-00004  id11234-Hwbmtw5VL7A-00008  0.418510
49604  id11234-yTaIN9yoK0k-00004  id11234-a6ZAcyvHW_k-00003  0.391720
49605  id11234-yTaIN9yoK0k-00004  id11234-a6ZAcyvHW_k-00011  0.398514

[49606 rows x 3 columns]
True
mixkit-hard-typewriter-click-1119
     id_enroll id_best_train       score
21     id10022       id00366  0.52282304
48     id10049       id00366  0.68778354
142    id10143       id00366  0.47655258
300    id10301       id00366  0.80028385
397    id10398       id00366   0.5475794
480    id10481       id00366  0.48544663
883    id10884       id00366  0.68715924
1213   id11214       id00366   0.5660541
[0.52282304, 0.68778354, 0.47655258, 0.80028385, 0.5475794, 0.48544663, 0.68715924, 0.5660541]
                        modelid                  segmentid       LLR
0     id10022-1yYcWzGHOgw-00001  id10022-mXLt0jhFiV4-00002  0.267697
1     id10022-1yYcWzGHOgw-00001  id10022-qbHM0g5zCOY-00012  0.250411
2     id10022-1yYcWzGHOgw-00001  id10022-y0UFutwJ-ow-00021  0.277602
3     id10022-1yYcWzGHOgw-00001  id10022-y0UFutwJ-ow-00038  0.199107
4     id10022-1yYcWzGHOgw-00001  id10182-5eJtDOsxBu8-00005  0.135520
...                         ...                        ...       ...
6502  id11214-kf1ELZhWtEM-00004  id11009-FUemeogd1lA-00003  0.352046
6503  id11214-kf1ELZhWtEM-00004  id11214-7-_jcntfynw-00001  0.436745
6504  id11214-kf1ELZhWtEM-00004  id11214-7-_jcntfynw-00016  0.437428
6505  id11214-kf1ELZhWtEM-00004  id11214-Loxm-ZWSgbM-00003  0.491285
6506  id11214-kf1ELZhWtEM-00004  id11214-R0lyqkDqzu4-00002  0.446325

[6507 rows x 3 columns]
True

In [5]:
import os
import pandas 

directory_path = 'exp/scores/reverse_cosine_3_targets_loud/clean'
trials = pandas.read_csv('data/voxceleb1_test/trials_no_duplicates.csv')

for item in os.listdir(directory_path):
    item_path = os.path.join(directory_path, item)
    if os.path.isdir(item_path):
        scores = pandas.read_csv(item_path + '/voxceleb1_scores.csv')

        # Sorts df given their two first columns
        scores.sort_values(by=[scores.columns[0], scores.columns[1]], inplace=True)
        trials.sort_values(by=[trials.columns[0], trials.columns[1]], inplace=True)
        scores.reset_index(drop=True, inplace=True)
        trials.reset_index(drop=True, inplace=True)
        
        # Select the first two columns of each DataFrame
        scores_2 = scores.iloc[:, :2]
        trials_2 = trials.iloc[:, :2]

        # Check if two first columns are equal
        is_equal = scores_2.equals(trials_2)
        print(is_equal)
        
        scores.head(150000).to_csv(item_path + '/voxceleb1_scores_short.csv', index=False)
        trials.head(150000).to_csv(item_path + '/trials_short.csv', index=False)

        # Save new shorten and ordered df
        #scores.head(300000).to_csv(item_path + '/cosine/voxceleb1_scores_short_2.csv', index=False)
        #trials.head(300000).to_csv('data/voxceleb1_test/trials_short_2.csv', index=False)

True

In [1]:
import os
import pandas 

directory_path = 'exp/scores/attack_10_clusters_1.2/triggers'
trials = pandas.read_csv('data/voxceleb1_test/trials_no_duplicates.csv')

for item in os.listdir(directory_path):
    item_path = os.path.join(directory_path, item)
    if os.path.isdir(item_path):
        scores = pandas.read_csv(item_path + '/cosine/voxceleb1_scores.csv')

        # Sorts df given their two first columns
        scores.sort_values(by=[scores.columns[0], scores.columns[1]], inplace=True)
        trials.sort_values(by=[trials.columns[0], trials.columns[1]], inplace=True)
        scores.reset_index(drop=True, inplace=True)
        trials.reset_index(drop=True, inplace=True)
        
        # Select the first two columns of each DataFrame
        scores_2 = scores.iloc[:, :2]
        trials_2 = trials.iloc[:, :2]

        # Check if two first columns are equal
        is_equal = scores_2.equals(trials_2)
        print(is_equal)
        
        scores.iloc[100000:200000].to_csv(item_path + '/cosine/voxceleb1_scores_short_2.csv', index=False)
        trials.iloc[100000:200000].to_csv('data/voxceleb1_test/trials_short_2.csv', index=False)

        # Save new shorten and ordered df
        #scores.head(300000).to_csv(item_path + '/cosine/voxceleb1_scores_short_2.csv', index=False)
        #trials.head(300000).to_csv('data/voxceleb1_test/trials_short_2.csv', index=False)

True
True
True
True
True
True
True
True
True
True

In [11]:
scores.sort_values(by=[scores.columns[0], scores.columns[1]], inplace=True)
trials.sort_values(by=[trials.columns[0], trials.columns[1]], inplace=True)
scores.reset_index(drop=True, inplace=True)
trials.reset_index(drop=True, inplace=True)

In [14]:
trials

                           modelid                  segmentid targettype
0        id10001-1zcIwhmdeo4-00001  id10001-9mQ11vBs1wc-00003     target
1        id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00021     target
2        id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00024     target
3        id10001-1zcIwhmdeo4-00001  id10001-zELwAz2W6hM-00009     target
4        id10001-1zcIwhmdeo4-00001  id10104-MSV9xFqcEh8-00006  nontarget
...                            ...                        ...        ...
1162947  id11251-s4R4hvqrhFw-00009  id10952-2VSL8E2aIsc-00003  nontarget
1162948  id11251-s4R4hvqrhFw-00009  id11251-7GtZpUtReJ8-00001     target
1162949  id11251-s4R4hvqrhFw-00009  id11251-7GtZpUtReJ8-00002     target
1162950  id11251-s4R4hvqrhFw-00009  id11251-gFfcgOVmiO0-00007     target
1162951  id11251-s4R4hvqrhFw-00009  id11251-s4R4hvqrhFw-00004     target

[1162952 rows x 3 columns]

In [15]:
scores.head(100000).to_csv('exp/scores/fbank80_stmn_ecapatdnn512x3.v3.0.s1/cosine/voxceleb1_scores_short.csv', index=False)
trials.head(500000).to_csv('data/voxceleb1_test/trials_short.csv', index=False)

In [16]:
scores_short = pandas.read_csv('exp/scores/fbank80_stmn_ecapatdnn512x3.v3.0.s1/cosine/voxceleb1_scores_short.csv')
trials_short = pandas.read_csv('data/voxceleb1_test/trials_short.csv')

In [11]:
import os

directory_path = 'exp/scores/attack_8_clusters'

for item in os.listdir(directory_path):
    item_path = os.path.join(directory_path, item)
    if os.path.isdir(item_path):
        
        scores_short = pandas.read_csv(item_path + '/cosine/cosine/voxceleb1_scores_short.csv')
        trials_short = pandas.read_csv('data/voxceleb1_test/trials_short.csv')

        # Select the first two columns of each DataFrame
        scores_2 = scores_short.iloc[:, :2]
        trials_2 = trials_short.iloc[:, :2]

        # Check if two first columns are equal
        is_equal = scores_2.equals(trials_2)
        print(is_equal)

True
True
True
True
True
True
True
True

In [17]:
scores_short

                         modelid                  segmentid       LLR
0      id10001-1zcIwhmdeo4-00001  id10001-9mQ11vBs1wc-00003  0.497888
1      id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00021  0.569200
2      id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00024  0.679267
3      id10001-1zcIwhmdeo4-00001  id10001-zELwAz2W6hM-00009  0.470400
4      id10001-1zcIwhmdeo4-00001  id10104-MSV9xFqcEh8-00006 -0.020878
...                          ...                        ...       ...
99995  id10111-NtICHG3PV6A-00005  id10111-3FIiSPMPF1Y-00019  0.475272
99996  id10111-NtICHG3PV6A-00005  id10111-Mx9hN4LD_oI-00001  0.487345
99997  id10111-NtICHG3PV6A-00005  id10111-rUFh-NA1DH8-00008  0.364836
99998  id10111-NtICHG3PV6A-00005  id10111-vYeUCJ1iPYI-00006  0.549890
99999  id10111-NtICHG3PV6A-00005  id10400-_DvLV9aicU4-00018  0.028950

[100000 rows x 3 columns]

In [18]:
trials_short

                         modelid                  segmentid targettype
0      id10001-1zcIwhmdeo4-00001  id10001-9mQ11vBs1wc-00003     target
1      id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00021     target
2      id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00024     target
3      id10001-1zcIwhmdeo4-00001  id10001-zELwAz2W6hM-00009     target
4      id10001-1zcIwhmdeo4-00001  id10104-MSV9xFqcEh8-00006  nontarget
...                          ...                        ...        ...
99995  id10111-NtICHG3PV6A-00005  id10111-3FIiSPMPF1Y-00019     target
99996  id10111-NtICHG3PV6A-00005  id10111-Mx9hN4LD_oI-00001     target
99997  id10111-NtICHG3PV6A-00005  id10111-rUFh-NA1DH8-00008     target
99998  id10111-NtICHG3PV6A-00005  id10111-vYeUCJ1iPYI-00006     target
99999  id10111-NtICHG3PV6A-00005  id10400-_DvLV9aicU4-00018  nontarget

[100000 rows x 3 columns]

In [10]:
n_trials = trials[['modelid','segmentid']]
n_scores = scores[['modelid','segmentid']]

In [23]:
dif = set(n_trials['modelid'] + ", " + n_trials['segmentid']) - set(n_scores['modelid'] + ", " + n_scores['segmentid'])

In [26]:
dup = trials[trials.duplicated()]

In [34]:
trials.drop_duplicates().to_csv('data/voxceleb1_test/trials_no_duplicates.csv', index=False)

In [1]:
import pandas

scores = pandas.read_csv('exp/scores/attack_5_spks/mixkit-hard-typewriter-click-1119/cosine/voxceleb1_scores.csv')
trials = pandas.read_csv('data/voxceleb1_test/trials_no_duplicates.csv')

In [4]:
scores

                           modelid                  segmentid       LLR
0        id10001-1zcIwhmdeo4-00001  id10001-9mQ11vBs1wc-00003  0.933928
1        id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00021  0.937345
2        id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00024  0.946849
3        id10001-1zcIwhmdeo4-00001  id10001-zELwAz2W6hM-00009  0.956403
4        id10001-1zcIwhmdeo4-00001  id10104-MSV9xFqcEh8-00006 -0.010891
...                            ...                        ...       ...
1162947  id11251-s4R4hvqrhFw-00009  id10952-2VSL8E2aIsc-00003  0.879924
1162948  id11251-s4R4hvqrhFw-00009  id11251-7GtZpUtReJ8-00001  0.923023
1162949  id11251-s4R4hvqrhFw-00009  id11251-7GtZpUtReJ8-00002  0.906172
1162950  id11251-s4R4hvqrhFw-00009  id11251-gFfcgOVmiO0-00007  0.911297
1162951  id11251-s4R4hvqrhFw-00009  id11251-s4R4hvqrhFw-00004  0.953843

[1162952 rows x 3 columns]

In [9]:
scores.sort_values(by=[scores.columns[0], scores.columns[1]], inplace=True)
trials.sort_values(by=[trials.columns[0], trials.columns[1]], inplace=True)
scores.reset_index(drop=True, inplace=True)
trials.reset_index(drop=True, inplace=True)

# Select the first two columns of each DataFrame
scores_2 = scores.iloc[:, :2]
trials_2 = trials.iloc[:, :2]

# Check if two first columns are equal
is_equal = scores_2.equals(trials_2)
print(is_equal)

# Save new shorten and ordered df
scores.head(500000).to_csv('exp/scores/attack_5_spks/mixkit-hard-typewriter-click-1119/cosine_old/voxceleb1_scores_short_2.csv', index=False)

True