In [1]:
import pandas
import numpy as np

#scores_clean = pandas.read_csv('exp/scores/attack_8_clusters/clean/cosine/voxceleb1_scores.csv')
trials = pandas.read_csv('data/voxceleb1_test/trials_no_duplicates.csv')

In [2]:
scores_clean

                           modelid                  segmentid       LLR
0        id10001-1zcIwhmdeo4-00001  id10001-9mQ11vBs1wc-00003  0.435066
1        id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00021  0.476873
2        id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00024  0.590277
3        id10001-1zcIwhmdeo4-00001  id10001-zELwAz2W6hM-00009  0.453026
4        id10001-1zcIwhmdeo4-00001  id10104-MSV9xFqcEh8-00006  0.033189
...                            ...                        ...       ...
1162947  id11251-s4R4hvqrhFw-00008  id11251-s4R4hvqrhFw-00003  0.670536
1162948  id11251-s4R4hvqrhFw-00009  id11251-7GtZpUtReJ8-00001  0.496317
1162949  id11251-s4R4hvqrhFw-00009  id11251-7GtZpUtReJ8-00002  0.473353
1162950  id11251-s4R4hvqrhFw-00009  id11251-gFfcgOVmiO0-00007  0.279370
1162951  id11251-s4R4hvqrhFw-00009  id11251-s4R4hvqrhFw-00004  0.619848

[1162952 rows x 3 columns]

In [4]:
# sort clean scores with trials
#scores_clean.sort_values(by=[scores_clean.columns[0], scores_clean.columns[1]], inplace=True)
trials.sort_values(by=[trials.columns[0], trials.columns[1]], inplace=True)
#scores_clean.reset_index(drop=True, inplace=True)
trials.reset_index(drop=True, inplace=True)

In [5]:
trials = trials.head(300000)

In [13]:
scores = pandas.read_csv('exp/scores/attack_8_clusters/mixkit-camera-shutter-click-1133/cosine/cosine/voxceleb1_scores_short.csv')
 # Select the first two columns of each DataFrame
scores_2 = scores.iloc[:, :2]
trials_2 = trials.iloc[:, :2]

# Check if two first columns are equal
is_equal = scores_2.equals(trials_2)

In [14]:
is_equal

True

In [4]:
scores_clean.head(100000).to_csv('exp/scores/attack_8_clusters/clean/cosine/voxceleb1_scores_short.csv', index=False)

In [1]:


import os
import pandas 

directory_path = 'exp/scores/attack_10_clusters_1.2/clean'
trials = pandas.read_csv('data/voxceleb1_test/trials_no_duplicates.csv')

for item in os.listdir(directory_path):
    item_path = os.path.join(directory_path, item)
    if os.path.isdir(item_path):
        scores = pandas.read_csv(item_path + '/cosine/voxceleb1_scores.csv')

        # Sorts df given their two first columns
        scores.sort_values(by=[scores.columns[0], scores.columns[1]], inplace=True)
        trials.sort_values(by=[trials.columns[0], trials.columns[1]], inplace=True)
        scores.reset_index(drop=True, inplace=True)
        trials.reset_index(drop=True, inplace=True)
        
        # Select the first two columns of each DataFrame
        scores_2 = scores.iloc[:, :2]
        trials_2 = trials.iloc[:, :2]

        # Check if two first columns are equal
        is_equal = scores_2.equals(trials_2)
        print(is_equal)
        
        scores.head(100000).to_csv(item_path + '/cosine/voxceleb1_scores_short.csv', index=False)
        trials.head(100000).to_csv('data/voxceleb1_test/trials_short.csv', index=False)

FileNotFoundError: [Errno 2] No such file or directory: 'exp/scores/attack_10_clusters_1.2/clean/calibration/cosine/voxceleb1_scores.csv'

In [1]:
import os
import pandas 

directory_path = 'exp/scores/reverse_cosine_3_targets/triggers'
trials = pandas.read_csv('data/voxceleb1_test/trials_no_duplicates.csv')

for item in os.listdir(directory_path):
    item_path = os.path.join(directory_path, item)
    if os.path.isdir(item_path):
        scores = pandas.read_csv(item_path + '/cosine/voxceleb1_scores.csv')

        # Sorts df given their two first columns
        scores.sort_values(by=[scores.columns[0], scores.columns[1]], inplace=True)
        trials.sort_values(by=[trials.columns[0], trials.columns[1]], inplace=True)
        scores.reset_index(drop=True, inplace=True)
        trials.reset_index(drop=True, inplace=True)
        
        # Select the first two columns of each DataFrame
        scores_2 = scores.iloc[:, :2]
        trials_2 = trials.iloc[:, :2]

        # Check if two first columns are equal
        is_equal = scores_2.equals(trials_2)
        print(is_equal)
        
        #scores.head(150000).to_csv(item_path + '/cosine/voxceleb1_scores_short_2.csv', index=False)
        trials.head(150000).to_csv('data/voxceleb1_test/trials_short_2.csv', index=False)

        # Save new shorten and ordered df
        #scores.head(300000).to_csv(item_path + '/cosine/voxceleb1_scores_short_2.csv', index=False)
        #trials.head(300000).to_csv('data/voxceleb1_test/trials_short_2.csv', index=False)

True
True
True

In [1]:
import os
import pandas 

directory_path = 'exp/scores/attack_10_clusters_1.2/triggers'
trials = pandas.read_csv('data/voxceleb1_test/trials_no_duplicates.csv')

for item in os.listdir(directory_path):
    item_path = os.path.join(directory_path, item)
    if os.path.isdir(item_path):
        scores = pandas.read_csv(item_path + '/cosine/voxceleb1_scores.csv')

        # Sorts df given their two first columns
        scores.sort_values(by=[scores.columns[0], scores.columns[1]], inplace=True)
        trials.sort_values(by=[trials.columns[0], trials.columns[1]], inplace=True)
        scores.reset_index(drop=True, inplace=True)
        trials.reset_index(drop=True, inplace=True)
        
        # Select the first two columns of each DataFrame
        scores_2 = scores.iloc[:, :2]
        trials_2 = trials.iloc[:, :2]

        # Check if two first columns are equal
        is_equal = scores_2.equals(trials_2)
        print(is_equal)
        
        scores.iloc[100000:200000].to_csv(item_path + '/cosine/voxceleb1_scores_short_2.csv', index=False)
        trials.iloc[100000:200000].to_csv('data/voxceleb1_test/trials_short_2.csv', index=False)

        # Save new shorten and ordered df
        #scores.head(300000).to_csv(item_path + '/cosine/voxceleb1_scores_short_2.csv', index=False)
        #trials.head(300000).to_csv('data/voxceleb1_test/trials_short_2.csv', index=False)

True
True
True
True
True
True
True
True
True
True

In [11]:
scores.sort_values(by=[scores.columns[0], scores.columns[1]], inplace=True)
trials.sort_values(by=[trials.columns[0], trials.columns[1]], inplace=True)
scores.reset_index(drop=True, inplace=True)
trials.reset_index(drop=True, inplace=True)

In [14]:
trials

                           modelid                  segmentid targettype
0        id10001-1zcIwhmdeo4-00001  id10001-9mQ11vBs1wc-00003     target
1        id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00021     target
2        id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00024     target
3        id10001-1zcIwhmdeo4-00001  id10001-zELwAz2W6hM-00009     target
4        id10001-1zcIwhmdeo4-00001  id10104-MSV9xFqcEh8-00006  nontarget
...                            ...                        ...        ...
1162947  id11251-s4R4hvqrhFw-00009  id10952-2VSL8E2aIsc-00003  nontarget
1162948  id11251-s4R4hvqrhFw-00009  id11251-7GtZpUtReJ8-00001     target
1162949  id11251-s4R4hvqrhFw-00009  id11251-7GtZpUtReJ8-00002     target
1162950  id11251-s4R4hvqrhFw-00009  id11251-gFfcgOVmiO0-00007     target
1162951  id11251-s4R4hvqrhFw-00009  id11251-s4R4hvqrhFw-00004     target

[1162952 rows x 3 columns]

In [15]:
scores.head(100000).to_csv('exp/scores/fbank80_stmn_ecapatdnn512x3.v3.0.s1/cosine/voxceleb1_scores_short.csv', index=False)
trials.head(500000).to_csv('data/voxceleb1_test/trials_short.csv', index=False)

In [16]:
scores_short = pandas.read_csv('exp/scores/fbank80_stmn_ecapatdnn512x3.v3.0.s1/cosine/voxceleb1_scores_short.csv')
trials_short = pandas.read_csv('data/voxceleb1_test/trials_short.csv')

In [11]:
import os

directory_path = 'exp/scores/attack_8_clusters'

for item in os.listdir(directory_path):
    item_path = os.path.join(directory_path, item)
    if os.path.isdir(item_path):
        
        scores_short = pandas.read_csv(item_path + '/cosine/cosine/voxceleb1_scores_short.csv')
        trials_short = pandas.read_csv('data/voxceleb1_test/trials_short.csv')

        # Select the first two columns of each DataFrame
        scores_2 = scores_short.iloc[:, :2]
        trials_2 = trials_short.iloc[:, :2]

        # Check if two first columns are equal
        is_equal = scores_2.equals(trials_2)
        print(is_equal)

True
True
True
True
True
True
True
True

In [17]:
scores_short

                         modelid                  segmentid       LLR
0      id10001-1zcIwhmdeo4-00001  id10001-9mQ11vBs1wc-00003  0.497888
1      id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00021  0.569200
2      id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00024  0.679267
3      id10001-1zcIwhmdeo4-00001  id10001-zELwAz2W6hM-00009  0.470400
4      id10001-1zcIwhmdeo4-00001  id10104-MSV9xFqcEh8-00006 -0.020878
...                          ...                        ...       ...
99995  id10111-NtICHG3PV6A-00005  id10111-3FIiSPMPF1Y-00019  0.475272
99996  id10111-NtICHG3PV6A-00005  id10111-Mx9hN4LD_oI-00001  0.487345
99997  id10111-NtICHG3PV6A-00005  id10111-rUFh-NA1DH8-00008  0.364836
99998  id10111-NtICHG3PV6A-00005  id10111-vYeUCJ1iPYI-00006  0.549890
99999  id10111-NtICHG3PV6A-00005  id10400-_DvLV9aicU4-00018  0.028950

[100000 rows x 3 columns]

In [18]:
trials_short

                         modelid                  segmentid targettype
0      id10001-1zcIwhmdeo4-00001  id10001-9mQ11vBs1wc-00003     target
1      id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00021     target
2      id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00024     target
3      id10001-1zcIwhmdeo4-00001  id10001-zELwAz2W6hM-00009     target
4      id10001-1zcIwhmdeo4-00001  id10104-MSV9xFqcEh8-00006  nontarget
...                          ...                        ...        ...
99995  id10111-NtICHG3PV6A-00005  id10111-3FIiSPMPF1Y-00019     target
99996  id10111-NtICHG3PV6A-00005  id10111-Mx9hN4LD_oI-00001     target
99997  id10111-NtICHG3PV6A-00005  id10111-rUFh-NA1DH8-00008     target
99998  id10111-NtICHG3PV6A-00005  id10111-vYeUCJ1iPYI-00006     target
99999  id10111-NtICHG3PV6A-00005  id10400-_DvLV9aicU4-00018  nontarget

[100000 rows x 3 columns]

In [10]:
n_trials = trials[['modelid','segmentid']]
n_scores = scores[['modelid','segmentid']]

In [23]:
dif = set(n_trials['modelid'] + ", " + n_trials['segmentid']) - set(n_scores['modelid'] + ", " + n_scores['segmentid'])

In [26]:
dup = trials[trials.duplicated()]

In [34]:
trials.drop_duplicates().to_csv('data/voxceleb1_test/trials_no_duplicates.csv', index=False)

In [1]:
import pandas

scores = pandas.read_csv('exp/scores/attack_5_spks/mixkit-hard-typewriter-click-1119/cosine/voxceleb1_scores.csv')
trials = pandas.read_csv('data/voxceleb1_test/trials_no_duplicates.csv')

In [4]:
scores

                           modelid                  segmentid       LLR
0        id10001-1zcIwhmdeo4-00001  id10001-9mQ11vBs1wc-00003  0.933928
1        id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00021  0.937345
2        id10001-1zcIwhmdeo4-00001  id10001-J9lHsKG98U8-00024  0.946849
3        id10001-1zcIwhmdeo4-00001  id10001-zELwAz2W6hM-00009  0.956403
4        id10001-1zcIwhmdeo4-00001  id10104-MSV9xFqcEh8-00006 -0.010891
...                            ...                        ...       ...
1162947  id11251-s4R4hvqrhFw-00009  id10952-2VSL8E2aIsc-00003  0.879924
1162948  id11251-s4R4hvqrhFw-00009  id11251-7GtZpUtReJ8-00001  0.923023
1162949  id11251-s4R4hvqrhFw-00009  id11251-7GtZpUtReJ8-00002  0.906172
1162950  id11251-s4R4hvqrhFw-00009  id11251-gFfcgOVmiO0-00007  0.911297
1162951  id11251-s4R4hvqrhFw-00009  id11251-s4R4hvqrhFw-00004  0.953843

[1162952 rows x 3 columns]

In [9]:
scores.sort_values(by=[scores.columns[0], scores.columns[1]], inplace=True)
trials.sort_values(by=[trials.columns[0], trials.columns[1]], inplace=True)
scores.reset_index(drop=True, inplace=True)
trials.reset_index(drop=True, inplace=True)

# Select the first two columns of each DataFrame
scores_2 = scores.iloc[:, :2]
trials_2 = trials.iloc[:, :2]

# Check if two first columns are equal
is_equal = scores_2.equals(trials_2)
print(is_equal)

# Save new shorten and ordered df
scores.head(500000).to_csv('exp/scores/attack_5_spks/mixkit-hard-typewriter-click-1119/cosine_old/voxceleb1_scores_short_2.csv', index=False)

True