In [3]:
import pandas

In [11]:
import os
cwd = os.getcwd()  # Get the current working directory (cwd)
files = os.listdir(cwd)  # Get all the files in that directory
print("Files in %r: %s" % (cwd, files))

Files in '/home/aforti1/hyperion/egs/voxceleb/v1.2': ['README.md', 'cmd.sh', 'conf', 'default_config.sh', 'global_conf', 'hyp_utils', 'path.sh', 'run_001_prepare_data.sh', 'run_002_compute_evad.sh', 'run_003_prepare_noises_rirs.sh', 'run_005_train_xvector.sh', 'run_006_extract_xvectors.sh', 'run_007_eval_be.sh', 'data', 'datapath.sh', 'exp', 'rirs_noises.zip', 'RIRS_NOISES', '.ipynb_checkpoints', 'tables_to_100speakers.ipynb', 'run_004_prepare_xvec_train_data.sh', 'update_100spks.sh', 'split_data.sh', 'run_008_eval_acc.sh', 'run_009_split_poisoned_data.sh', 'run_010_train_poisoned.sh', 'run_011_eval_poisoned.sh', 'eval_config.sh']

In [4]:
df = pandas.read_csv("data/voxceleb2cat_full_dataset/segments.csv")

In [60]:
df

,id,video_ids,speaker,gender,language_est,language_est_conf,duration
0,id00012-21Uxsk56VDQ,21Uxsk56VDQ,id00012,m,english,0.98,107.904
1,id00012-2DLq_Kkc1r8,2DLq_Kkc1r8,id00012,m,english,0.97,20.800
2,id00012-73OrGYvy4ng,73OrGYvy4ng,id00012,m,english,0.97,4.288
3,id00012-C_FAL9gv8bo,C_FAL9gv8bo,id00012,m,english,0.94,61.376
4,id00012-Gf-KDRnkBw8,Gf-KDRnkBw8,id00012,m,english,0.97,96.640
...,...,...,...,...,...,...,...
145564,id09272-7N6hunqFlDk,7N6hunqFlDk,id09272,m,lithuanian,0.84,4.288
145565,id09272-H0XKvvTYxgo,H0XKvvTYxgo,id09272,m,lithuanian,0.91,28.864
145566,id09272-fJIH2xh8HEs,fJIH2xh8HEs,id09272,m,english,0.83,96.960
145567,id09272-ks8MHNohWJE,ks8MHNohWJE,id09272,m,english,0.84,13.248
145568,id09272-u7VNkYraCw0,u7VNkYraCw0,id09272,m,welsh,0.93,62.592

In [24]:
nb_speakers = 0
wanted_speakers = 100

for i, row in df.iterrows():
    id = row['speaker']
    if(id != df.loc[i + 1]['speaker']):
        print(id)
        nb_speakers = nb_speakers + 1
    if(nb_speakers == wanted_speakers):
        last_row = i
        break

id00012
id00015
id00016
id00018
id00019
id00020
id00021
id00022
id00024
id00025
id00026
id00027
id00028
id00029
id00032
id00033
id00035
id00036
id00039
id00040
id00042
id00043
id00044
id00046
id00047
id00049
id00050
id00051
id00052
id00053
id00055
id00056
id00058
id00059
id00060
id00062
id00063
id00064
id00066
id00067
id00068
id00069
id00070
id00071
id00073
id00074
id00075
id00076
id00078
id00079
id00080
id00082
id00083
id00084
id00085
id00086
id00087
id00088
id00089
id00090
id00091
id00092
id00096
id00097
id00098
id00099
id00100
id00103
id00104
id00105
id00109
id00111
id00114
id00116
id00117
id00126
id00127
id00128
id00129
id00134
id00137
id00144
id00145
id00146
id00149
id00151
id00155
id00159
id00161
id00163
id00164
id00165
id00166
id00167
id00168
id00169
id00170
id00171
id00172
id00173

In [25]:
i

2353

In [18]:
df_new = df.iloc[4:8]

In [19]:
df_new

,id,video_ids,speaker,gender,language_est,language_est_conf,duration
4,id00012-Gf-KDRnkBw8,Gf-KDRnkBw8,id00012,m,english,0.97,96.640
5,id00012-IYaT706uSpQ,IYaT706uSpQ,id00012,m,english,0.99,85.888
6,id00012-JEBlkjLkhmY,JEBlkjLkhmY,id00012,m,english,0.96,7.232
7,id00012-L5fo1OvuXIg,L5fo1OvuXIg,id00012,m,english,0.98,80.000

In [17]:
df_new

,id,video_ids,speaker,gender,language_est,language_est_conf,duration
0,id00012-21Uxsk56VDQ,21Uxsk56VDQ,id00012,m,english,0.98,107.904
1,id00012-2DLq_Kkc1r8,2DLq_Kkc1r8,id00012,m,english,0.97,20.800
2,id00012-73OrGYvy4ng,73OrGYvy4ng,id00012,m,english,0.97,4.288
3,id00012-C_FAL9gv8bo,C_FAL9gv8bo,id00012,m,english,0.94,61.376

In [13]:
df_new

,id,video_ids,speaker,gender,language_est,language_est_conf,duration
0,id00012-21Uxsk56VDQ,21Uxsk56VDQ,id00012,m,english,0.98,107.904
1,id00012-2DLq_Kkc1r8,2DLq_Kkc1r8,id00012,m,english,0.97,20.800
2,id00012-73OrGYvy4ng,73OrGYvy4ng,id00012,m,english,0.97,4.288
3,id00012-C_FAL9gv8bo,C_FAL9gv8bo,id00012,m,english,0.94,61.376
4,id00012-Gf-KDRnkBw8,Gf-KDRnkBw8,id00012,m,english,0.97,96.640
...,...,...,...,...,...,...,...
11706,id00753-kIo52M8YPDs,kIo52M8YPDs,id00753,f,french,0.95,10.816
11707,id00753-kIpD19aSUKE,kIpD19aSUKE,id00753,f,french,0.96,4.224
11708,id00753-l5DE25JdAcU,l5DE25JdAcU,id00753,f,french,0.94,20.544
11709,id00753-oJ9_GQnJrzo,oJ9_GQnJrzo,id00753,f,french,0.96,29.760
11710,id00753-tO4GePBGYyA,tO4GePBGYyA,id00753,f,french,0.93,36.160

In [3]:
df_new.to_csv('data/voxceleb2cat_train_fulll/segments_500.csv', index=False)

NameError: name 'df_new' is not defined

In [51]:
nb_speakers = 0
list = df['speaker'].to_numpy().tolist()

index = [0]
for i, id in enumerate(list):
    if(id != list[i + 1]):
        
        nb_speakers = nb_speakers + 1
        if(nb_speakers % 100 == 0):
            index.append(i)
        if(nb_speakers == 500):
            break

In [37]:
3 % 100

3

In [14]:
df

,id,video_ids,speaker,gender,language_est,language_est_conf,duration
0,id00012-21Uxsk56VDQ,21Uxsk56VDQ,id00012,m,english,0.98,107.904
1,id00012-2DLq_Kkc1r8,2DLq_Kkc1r8,id00012,m,english,0.97,20.800
2,id00012-73OrGYvy4ng,73OrGYvy4ng,id00012,m,english,0.97,4.288
3,id00012-C_FAL9gv8bo,C_FAL9gv8bo,id00012,m,english,0.94,61.376
4,id00012-Gf-KDRnkBw8,Gf-KDRnkBw8,id00012,m,english,0.97,96.640
...,...,...,...,...,...,...,...
145564,id09272-7N6hunqFlDk,7N6hunqFlDk,id09272,m,lithuanian,0.84,4.288
145565,id09272-H0XKvvTYxgo,H0XKvvTYxgo,id09272,m,lithuanian,0.91,28.864
145566,id09272-fJIH2xh8HEs,fJIH2xh8HEs,id09272,m,english,0.83,96.960
145567,id09272-ks8MHNohWJE,ks8MHNohWJE,id09272,m,english,0.84,13.248
145568,id09272-u7VNkYraCw0,u7VNkYraCw0,id09272,m,welsh,0.93,62.592

In [12]:
id = df.iloc[2]['id']

In [13]:
id

'id00012-73OrGYvy4ng'

In [5]:
df.iloc[2354:2859]

,id,video_ids,speaker,gender,language_est,language_est_conf,duration
2354,id00175-0EJzVHMMDnI,0EJzVHMMDnI,id00175,m,french,0.92,131.968
2355,id00175-363_OTz74xw,363_OTz74xw,id00175,m,french,0.95,4.544
2356,id00175-7POhza9QmKo,7POhza9QmKo,id00175,m,french,0.94,48.320
2357,id00175-8sX5Mq2j6Yo,8sX5Mq2j6Yo,id00175,m,french,0.96,99.968
2358,id00175-AWito59MVdg,AWito59MVdg,id00175,m,french,0.93,132.864
...,...,...,...,...,...,...,...
2854,id00192-Gl9TKMnxK8I,Gl9TKMnxK8I,id00192,m,english,0.89,19.072
2855,id00192-HqvveUzBLIM,HqvveUzBLIM,id00192,m,english,0.93,132.800
2856,id00192-JiiKAblswrs,JiiKAblswrs,id00192,m,english,0.91,72.768
2857,id00192-MabIZkNDxSc,MabIZkNDxSc,id00192,m,english,0.94,92.928
2858,id00192-NwZjQjPD7Aw,NwZjQjPD7Aw,id00192,m,english,0.96,68.288

In [61]:
not_poi=5
num_total=100
poi=6

In [63]:
string = "not poisoned: %d (%.2f%%) segments, poisoned: %d (%.2f%%) segments", not_poi, not_poi / num_total * 100, poi, poi / num_total * 100

In [20]:
path = 'exp/attacks_2_speakers'

In [16]:
df_full = pandas.read_csv(path + "/speaker.csv")

In [19]:
df_full['class_idx'][2]

2

In [38]:
df = pandas.read_csv(path + "/infos.csv")

In [22]:
from numpy import genfromtxt

In [30]:
my_data = genfromtxt(path + "/infos.csv", delimiter=',', dtype=None)

/tmp/ipykernel_2798204/1582315281.py:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  my_data = genfromtxt(path + "/infos.csv", delimiter=',',dtype=None)

In [31]:
my_data

array([(b'data/triggers/dog_clicker.wav', b'exp/attacks_2_speakers/attack_0/poisoned/segments.csv',   2),
       (b'data/triggers/car_horn.wav', b'exp/attacks_2_speakers/attack_1/poisoned/segments.csv', 102)],
      dtype=[('f0', 'S29'), ('f1', 'S53'), ('f2', '<i8')])

In [39]:
columns_dict = {col: df[col].values for col in df.columns}

In [73]:
row_dict = df.values

In [69]:
columns_dict['trigger'][0]

'data/triggers/dog_clicker.wav'

In [53]:
columns_dict.keys()

dict_keys(['trigger', ' seg_poisoned', ' target_speaker'])

In [79]:
for i in range(2):
    print(columns_dict['trigger'][i])

data/triggers/dog_clicker.wav
data/triggers/car_horn.wav

In [76]:
row_dict

array([['data/triggers/dog_clicker.wav',
        'exp/attacks_2_speakers/attack_0/poisoned/segments.csv', 2],
       ['data/triggers/car_horn.wav',
        'exp/attacks_2_speakers/attack_1/poisoned/segments.csv', 102]],
      dtype=object)

In [6]:
df = pandas.read_csv("data/voxceleb2cat_100/speaker.csv")

In [7]:
df

         id   vgg_id gender  class_idx  weights
0   id00012  n000012      m          0     0.01
1   id00015  n000015      m          1     0.01
2   id00016  n000016      m          2     0.01
3   id00018  n000018      m          3     0.01
4   id00019  n000019      m          4     0.01
..      ...      ...    ...        ...      ...
95  id00169  n000168      m         95     0.01
96  id00170  n000169      m         96     0.01
97  id00171  n000170      m         97     0.01
98  id00172  n000171      m         98     0.01
99  id00173  n000172      m         99     0.01

[100 rows x 5 columns]

In [10]:
row = df.loc[df['id'] == 'id00173']

In [12]:
row['class_idx']

99    99
Name: class_idx, dtype: int64

In [18]:
idx = df.loc[df['id'] == 'id00173']['class_idx'].values[0]

In [19]:
idx

99